### ISSUE TITLE
Migration to version 9.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/sale-reporting#30]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-9.0
# Modules to migrate
- [ ] sale_order_proforma_webkit
- [ ] sale_note_flow
- [ ] sale_order_webkit
- [ ] html_sale_product_note
- [ ] sale_comment_template #34
