### ISSUE TITLE
Migration to version 10.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/sale-reporting#35]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0
# Modules to migrate
- [ ] html_sale_product_note
- [ ] product_brand_sale_report - By @MPoch-PlanetaTIC - #93 
- [x] sale_comment_template - By @SimoRubi - #44 
- [ ] sale_note_flow
- [ ] sale_order_proforma_webkit
- [ ] sale_order_webkit

**Comment by SimoRubi** [comment]
Hi, I've fixed the #40 and made the new PR #44 for module sale_comment_template
