### ISSUE TITLE
Migration to version 11.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/sale-reporting#43]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

# Modules to migrate

- [ ] html_sale_product_note
- [x] sale_comment_template - By @xavierjimenez - #53 
- [ ] sale_note_flow
- [x] ~~sale_order_proforma_webkit~~ - Not needed - Already in core
- [x] ~~sale_order_webkit~~ Outdated engine
- [x] ~~sale_proforma_report~~ - Not needed - Already in core
- [x] sale_report_delivered > sale_report_delivered_subtotal - By @chienandalu - #50
